baseURL = "https://jandytenedora.github.io/"
languageCode = "en-gb"
title = "Jandy Tenedora"
theme = "hugo-book"
paginate = 10

disablePathToLower = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
  [markup.highlight]
    noClasses = false
    guessSyntax = true

[params]
  BookTheme = "light"
  BookSection = "*"
  BookSearch = true
  BookToC = true
  BookDateFormat = "2 January 2006"
  BookComments = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[menu]
  [[menu.before]]
    name = "About"
    pageRef = "/about"
    weight = 1
  [[menu.after]]
    name = "Graph"
    url = "/graph/"
    weight = 2
