baseURL = "https://jandytenedora.github.io/"
languageCode = "en-gb"
title = "Jandy Tenedora"
theme = "hugo-tufte"
paginate = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    guessSyntax = true

[params]
  subtitle = "Senior Data Engineer. Back to first principles."
  showSummary = true
  showPoweredBy = false
  math = false
  github = "JandyTenedora"
  linkedin = "jandytenedora"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[menu]
  [[menu.nav]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.nav]]
    name = "Graph"
    url = "/graph/"
    weight = 3
